--- #YAML:1.0
name: Class-Data-Reloadable
version: 0.04
author:
  - David Baird <cpan@riverside-cms.co.uk>
abstract: |-
  inheritable, overridable class data that survive reloads
license: perl
requires:
  Carp: 0
  Class::ISA: 0
  NEXT: 0
  Symbol: 0
  Test::Exception: 0
  Test::More: 0
  UNIVERSAL::require: 0
provides:
  Class::Data::Reloadable:
    file: lib/Class/Data/Reloadable.pm
    version: 0.04
generated_by: Module::Build version 0.2609
